#colorscheme red-phoenix
colorscheme solarized-dark-termcolors
add-highlighter global/ wrap -word
add-highlighter global/ number-lines -relative


#plugins

hook global WinSetOption filetype=(.*) %{
        rainbow-enable-window
}

#Suggested hook

hook global WinDisplay .* info-buffers

# Suggested mappings

map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'

# Suggested aliases

alias global bd delete-buffer
alias global bf buffer-first
alias global bl buffer-last
alias global bo buffer-only
alias global bo! buffer-only-force
