colorscheme solarized-dark
add-highlighter global/ wrap -word
add-highlighter global/ number-lines -relative

#plugins

hook global BufCreate .*[.](cl) %{
	set-option buffer filetype lisp
}

hook global WinSetOption filetype=(.*) %{
        rainbow-enable-window
}

hook global BufOpenFile .* %{
        modeline-parse
}

map global normal <c-a> ':inc-dec-modify-numbers + 1<ret>'
map global normal <c-x> ':inc-dec-modify-numbers - 1<ret>'

map global user w 'Z%yz:info -title "Buffer size (wc)" %sh{echo -n "$kak_reg_dquote" | wc | awk "{print \"r:\", \$1, \"w:\", \$2, \"b:\", \$3}"}<ret>' \
	-docstring 'show size of buffer (wc command)'

map global user c ':palette-status<ret>' -docstring 'Info about color'
map global user r ':list-registers<ret>' -docstring 'List register'

# TODO C
# https://github.com/kak-lsp/kak-lsp#configuration
eval %sh{kak-lsp --kakoune -s $kak_session}
