CompileFlags:
  Add:
    - -Wall
    - -Wno-variadic-macros
    - -Wextra
    - -Wunused
    - -Wpedantic
    - -Wno-empty-translation-unit

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    FastCheckFilter: Loose
    Add:
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
      - clang-analyzer-*
      - misc-*
      - bugprone-*
      - mpi-*
      - openmp-*
      # - concurrency-*
    Remove:
      - modernize-use-trailing-return-type
      - modernize-use-auto
      - readability-isolate-declaration
      - misc-use-anonymous-namespace
      - bugprone-switch-missing-default-case
      - readability-math-missing-parentheses

---
If:
  PathMatch: [.*\.c]
CompileFlags:
  Add: [-xc]

---
If:
  PathMatch: [.*\.h]
CompileFlags:
  Add: [-xc-header]

---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add: [-xc++, -Weffc++]
Diagnostics:
  ClangTidy:
    Add: cppcoreguidelines-*
