# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.

# AUTOCONFIG!!!
config.load_autoconfig()

config.set('content.cookies.accept', 'never', '*')
config.set('content.cookies.accept', 'no-unknown-3rdparty', 'chrome-devtools://*')
config.set('content.cookies.accept', 'all', 'https://searx.info/*')
config.set('content.cookies.accept', 'all', 'https://searx.xyz/*')
config.set('content.cookies.accept', 'all', 'https://paulgo.io/*')
config.set('content.cookies.store', True)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'no-unknown-3rdparty', 'devtools://*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0', 'https://*.slack.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString #Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
config.set('content.headers.user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0', 'https://docs.google.com/*')
config.set('content.headers.user_agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0', 'https://*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://drive.google.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')
config.set('editor.command', ['gsvim', '-c', 'normal {line}G{column0}1', '{file}'])

config.unbind('J', mode='normal')
config.unbind('K', mode='normal')
config.unbind('H', mode='normal')
config.unbind('L', mode='normal')
config.unbind('gJ', mode='normal')
config.unbind('gK', mode='normal')

config.bind('H', 'tab-prev', mode='normal')
config.bind('L', 'tab-next', mode='normal')
config.bind('gl', 'tab-move +', mode='normal')
config.bind('gh', 'tab-move -', mode='normal')
config.bind('J', 'back', mode='normal')
config.bind('K', 'forward', mode='normal')

config.bind('<Ctrl+r>', 'restart', mode='normal')
config.bind('<Ctrl+o>', 'set-cmd-text -s :open -b', mode='normal')
config.bind('ps', 'insert-text {primary}')
config.bind('ys', 'yank selection')

config.bind(',dm', 'open -t qute://log/?level=info')
config.bind(',db', 'open -t qute://bindings/')
config.bind(',dg', 'open -t chrome://gpu/')
config.bind(',dh', 'open -t qute://help/index.html')
config.bind(',dH', 'open -t qute://history')

config.bind(',m', 'spawn smplayer "{url}"', mode='normal')
config.bind(',M', 'hint links spawn -d smplayer "{hint-url}"')
config.bind(',s', 'config-cycle statusbar.show always never')
config.bind(',t', 'config-cycle tabs.show always never')
config.bind(',e', 'hint links spawn -d sh -c "wget -O - "{url}" | gsvim -"')
config.bind(',E', 'spawn -d sh -c "wget -O - "{url}" | gsvim -"')
config.bind(',r', 'hint links spawn -d sh -c "wget -O - "{url}" | w3m -T text/html -dump | gsvim -"')
config.bind(',R', 'spawn -d sh -c "wget -O - "{url}" | w3m -T text/html -dump | gsvim -"')
config.bind(',v', 'spawn -d vlc "{url}"')
config.bind(',V', 'hint links spawn -d vlc "{hint-url}"')

config.bind(',NH', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=1080]+bestaudio" "{hint-url}"')
config.bind(',NL', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=360]+bestaudio" "{hint-url}"')
config.bind(',NM', 'hint links spawn -d mpv --ytdl-format="bestaudio" --player-operation-mode=pseudo-gui "{hint-url}"')
config.bind(',Nh', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=720]+bestaudio" "{hint-url}"')
config.bind(',Nl', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=480]+bestaudio" "{hint-url}"')
config.bind(',Nm', 'hint links spawn -d mpv "{hint-url}"')
config.bind(',Nq', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=1440]+bestaudio" "{hint-url}"')
config.bind(',nH', 'spawn -d mpv --ytdl-format="bestvideo[height<=1080]+bestaudio" "{url}"')
config.bind(',nL', 'hint links spawn -d mpv --ytdl-format="bestvideo[height<=360]+bestaudio" "{url}"')
config.bind(',nM', 'spawn -d mpv --ytdl-format="bestaudio" --player-operation-mode=pseudo-gui "{url}"')
config.bind(',nh', 'spawn -d mpv --ytdl-format="bestvideo[height<=720]+bestaudio" "{url}"')
config.bind(',nl', 'spawn -d mpv --ytdl-format="bestvideo[height<=480]+bestaudio" "{url}"')
config.bind(',nm', 'spawn -d mpv "{url}"')
config.bind(',nq', 'spawn -d mpv --ytdl-format="bestvideo[height<=1440]+bestaudio" "{url}"')

#config.bind(',', '')

import dracula.draw
dracula.draw.blood(c, {
    'spacing': {
        'vertical': 4,
        'horizontal': 6
    }
})

config.set ('colors.webpage.darkmode.enabled', True)
config.set ('fonts.default_size', '12pt')

config.set('content.javascript.enabled', False, '*')
config.set('hints.chars', 'asdfjkl;')

config.set('url.default_page', 'https://searx.info')
config.set('url.searchengines',
        {'DEFAULT':'https://paulgo.io/search?q={}',
            'sf':'https://searx.xyz/search?q={}',
            'ps':'https://paulgo.io/search?q={}&language=pl-PL',
            'psf':'https://searx.xyz/search?q={}&language=pl-PL',
            'dg':'https://duckduckgo.com/?q={}',
            'dgp':'https://duckduckgo.com/?q={}&kl=pl-pl&t=h_&ia=web',
            'aw':'https://wiki.archlinux.org/index.php?search={}',
            'gh':'https://github.com/search?q={}',
            'yt':'https://youtube.com/results?search_query={}',
            'gw':'https://wiki.gentoo.org/index.php?search={}',
            'gp':'https://packages.gentoo.org/packages/search?q={}',
            'lb':'https://odysee.com/$/search?q={}'
            })

#Javascript in search engines and other useful websites
config.set('content.javascript.enabled', True, 'https://searx.info/*')
config.set('content.javascript.enabled', True, 'https://searx.xyz/*')
config.set('content.javascript.enabled', True, 'https://paulgo.io/*')
config.set('content.javascript.enabled', True, 'https://duckduckgo.com/*')
config.set('content.javascript.enabled', True, 'https://*.github.com/*')
config.set('content.javascript.enabled', True, 'https://meteo.pl/*')
config.set('content.javascript.enabled', True, 'https://odysee.com/*')
config.set('content.javascript.enabled', True, 'https://youtube.com/*')
