# TODO prettier colors

[bell]
color = "#023210"

[colors.cursor]
cursor = "#30ffff"
text = "#000000"

[colors.normal]
black = "#020406"
red = "#d01010"
green = "#10d010"
yellow = "#d0d010"
blue = "#001fff"
magenta = "#ff1fe0"
cyan = "#40e0e0"
white = "#dcdcdc"

[colors.bright]
black = "#1f2f3f"
red = "#ff4030"
green = "#2fff30"
yellow = "#f0ef60"
blue = "#3f5fff"
magenta = "#ff5aff"
cyan = "#56ffff"
white = "#ffffff"

[colors.primary]
background = "#000108"
bright_foreground = "#02aacd"
dim_foreground = "#020a0f"
foreground = "#0850ff"

[colors.search.matches]
background = "#002412"
foreground = "#0256ce"

[colors.selection]
background = "#0f8faf"
