(load "view.el")

;(define-key yas-minor-mode-map (kbd "C-c k") 'yas-expand)
(define-key global-map (kbd "C-c o") 'iedit-mode)
;(add-hook 'elpy-mode-hook
;    (lambda ()
;    (local-unset-key (kbd "M-TAB"))
;    (define-key elpy-mode-map (kbd "C-d") 'elpy-company-backend)))

(global-set-key (kbd "C-c k") 'kill-save-to-x-clipboard)
(global-set-key (kbd "C-c y") 'yank-from-x-clipboard)


(global-set-key '[(ctrl c) (ctrl \")]
                (lambda ()
                  (interactive)
                  (if (member 'refresh-svg-preview after-save-hook)
                      (progn
                        (remove-hook 'after-save-hook 'refresh-svg-preview t)
                        (message "No longer previewing on save."))
                    (progn
                      (add-hook 'after-save-hook 'refresh-svg-preview nil t)
                      (message "Previewing this SVG on save.")))))


(global-unset-key (kbd "C-h"))
(global-unset-key (kbd "C-x h"))
(global-unset-key (kbd "C-x f"))
(global-unset-key (kbd "C-x C-f"))
(global-set-key (kbd "C-x f") 'find-file)
(global-set-key (kbd "C-x C-f") 'set-fill-column)
(global-set-key (kbd "C-x h") 'help)
(global-set-key (kbd "C-x C-h") 'mark-whole-buffer)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)
(global-set-key (kbd "M-L") 'redraw-display)
(global-set-key (kbd "M-i") 'completion-at-point)
(global-set-key (kbd "C-M-i") 'tab-to-tab-stop)
(global-set-key (kbd "C-h") 'backward-delete-char-untabify)
;(global-unset-key (kbd "C-i"))
;(global-set-key (kbd "C-i") 'indent-line-function)

(global-set-key (kbd "C-x O")           'backward-other-window)
(global-set-key (kbd "C-x :")           'eval-sexp)
(global-set-key (kbd "C-<f10>")		'View-scroll-half-page-forward)
(global-set-key (kbd "C-<f9>")		'View-scroll-half-page-backward)
(global-set-key (kbd "<f34>")		'View-scroll-half-page-forward)
(global-set-key (kbd "<f33>")		'View-scroll-half-page-backward)
;(global-set-key (kbd "C-M-<f10>")	'redraw-display)

(global-set-key (kbd "H-@")		'pop-global-mark)
(global-set-key (kbd "H-B")		'list-buffers)
(global-set-key (kbd "H-c")		'save-buffers-kill-terminal)
(global-set-key (kbd "H-D")		'list-directory)
(global-set-key (kbd "H-E")		'eval-last-sexp)
(global-set-key (kbd "H-f")		'find-file)
(global-set-key (kbd "H-h")		'help)
(global-set-key (kbd "H-TAB")		'indent-rigidly)
;(global-set-key (kbd "H-K")		'kmacro-keymap)
(global-set-key (kbd "H-L")		'downcase-region)
(global-set-key (kbd "H-N")		'set-goal-column)
(global-set-key (kbd "H-O")		'backward-other-window)
(global-set-key (kbd "H-P")		'mark-page)
(global-set-key (kbd "H-Q")		'read-only-mode)
(global-set-key (kbd "H-R")		'recentf-open-files)
(global-set-key (kbd "H-S")		'save-buffer)
(global-set-key (kbd "H-T")		'transpose-lines)
(global-set-key (kbd "H-U")		'upcase-region)
(global-set-key (kbd "H-V")		'find-alternate-file)
(global-set-key (kbd "H-W")		'write-file)
(global-set-key (kbd "H-X")		'exchange-point-and-mark)
(global-set-key (kbd "H-Z")		'suspend-frame)
(global-set-key (kbd "H-S-SPC")		'rectangle-mark-mode)
(global-set-key (kbd "H-$")    		'set-selective-display)
(global-set-key (kbd "H-'")    		'expand-abbrev)
(global-set-key (kbd "H-(")    		'kmacro-start-macro)
(global-set-key (kbd "H-)")    		'kmacro-end-macro)
(global-set-key (kbd "H-*")    		'calc-dispatch)
(global-set-key (kbd "H-+")    		'balance-windows)
(global-set-key (kbd "H--")    		'shrink-window-if-larger-than-buffer)
(global-set-key (kbd "H-.")    		'set-fill-prefix)
(global-set-key (kbd "H-0")    		'delete-window)
(global-set-key (kbd "H-1")    		'delete-other-windows)
(global-set-key (kbd "H-2")    		'split-window-below)
(global-set-key (kbd "H-3")    		'split-window-right)
(global-set-key (kbd "H-4")    		'ctl-x-4-prefix)
(global-set-key (kbd "H-5")    		'ctl-x-5-prefix)
(global-set-key (kbd "H-6")    		'2C-command)
(global-set-key (kbd "H-;")    		'comment-set-column)
(global-set-key (kbd "H-<")    		'scroll-left)
(global-set-key (kbd "H-=")    		'what-cursor-position)
(global-set-key (kbd "H->")    		'scroll-right)
(global-set-key (kbd "H-[")    		'backward-page)
(global-set-key (kbd "H-]")    		'forward-page)
(global-set-key (kbd "H-^")    		'enlarge-window)
(global-set-key (kbd "H-`")    		'next-error)
(global-set-key (kbd "H-b")    		'switch-to-buffer)
(global-set-key (kbd "H-d")    		'dired)
(global-set-key (kbd "H-e")    		'kmacro-end-and-call-macro)
(global-set-key (kbd "H-F")    		'set-fill-column)
(global-set-key (kbd "H-H")    		'mark-whole-buffer)
(global-set-key (kbd "H-i")    		'insert-file)
(global-set-key (kbd "H-k")    		'kill-buffer)
(global-set-key (kbd "H-l")    		'count-lines-page)
(global-set-key (kbd "H-m")    		'compose-mail)
(global-set-key (kbd "H-o")    		'other-window)
(global-set-key (kbd "H-q")    		'kbd-macro-query)
(global-set-key (kbd "H-s")    		'save-some-buffers)
(global-set-key (kbd "H-u")    		'undo)
(global-set-key (kbd "H-v")    		'vc-prefix-map)
(global-set-key (kbd "H-z")    		'repeat)
(global-set-key (kbd "H-{")    		'shrink-window-horizontally)
(global-set-key (kbd "H-}")    		'enlarge-window-horizontally)
(global-set-key (kbd "H-DEL")		'backward-kill-sentence)
(global-set-key (kbd "H-SPC")		'pop-global-mark)
(global-set-key (kbd "H-+")		'text-scale-adjust)
(global-set-key (kbd "H--")		'text-scale-adjust)
(global-set-key (kbd "H-C-0")		'text-scale-adjust)
(global-set-key (kbd "H-C-;")		'comment-line)
(global-set-key (kbd "H-C-=")		'text-scale-adjust)
(global-set-key (kbd "H-<C-left>")	'previous-buffer)
(global-set-key (kbd "H-<C-right>")	'next-buffer)
(global-set-key (kbd "H-<left>")	'previous-buffer)
(global-set-key (kbd "H-<right>")	'next-buffer)

(define-key key-translation-map (kbd "H-RET")	(kbd "C-x RET"))
(define-key key-translation-map (kbd "H-ESC")	(kbd "C-x ESC"))
(define-key key-translation-map (kbd "H-8")  	(kbd "C-x 8"))
(define-key key-translation-map (kbd "H-a")  	(kbd "C-x a"))
(define-key key-translation-map (kbd "H-n")  	(kbd "C-x n"))
(define-key key-translation-map (kbd "H-p")  	(kbd "C-x p"))
(define-key key-translation-map (kbd "H-t")  	(kbd "C-x t"))
(define-key key-translation-map (kbd "H-r")  	(kbd "C-x r"))

;(define-key key-translation-map (kbd "ESC") (kbd "C-g"))
(global-set-key (kbd "H-g")		'keyboard-quit)


;(define-key key-translation-map (kbd "A-")	(kbd "C-M-"))

(global-set-key (kbd "A-i")		'backward-button)
(global-set-key (kbd "A-@")		'mark-sexp)
(global-set-key (kbd "A-a")		'beginning-of-defun)
(global-set-key (kbd "A-b")		'backward-sexp)
(global-set-key (kbd "A-c")		'exit-recursive-edit)
(global-set-key (kbd "A-d")		'down-list)
(global-set-key (kbd "A-e")		'end-of-defun)
(global-set-key (kbd "A-f")		'forward-sexp)
(global-set-key (kbd "A-h")		'mark-defun)
(global-set-key (kbd "A-j")		'default-indent-new-line)
(global-set-key (kbd "A-k")		'kill-sexp)
(global-set-key (kbd "A-l")		'reposition-window)
(global-set-key (kbd "A-n")		'forward-list)
(global-set-key (kbd "A-o")		'split-line)
(global-set-key (kbd "A-p")		'backward-list)
(global-set-key (kbd "A-r")		'isearch-backward-regexp)
(global-set-key (kbd "A-s")		'isearch-forward-regexp)
(global-set-key (kbd "A-t")		'transpose-sexps)
(global-set-key (kbd "A-u")		'backward-up-list)
(global-set-key (kbd "A-v")		'scroll-other-window)
(global-set-key (kbd "A-w")		'append-next-kill)
(global-set-key (kbd "A-\\")		'indent-region)
(global-set-key (kbd "A-S-v")		'scroll-other-window-down)
(global-set-key (kbd "A-SPC")		'mark-sexp)
(global-set-key (kbd "A-%")		'query-replace-regexp)
(global-set-key (kbd "A--")		'negative-argument)
(global-set-key (kbd "A-.")		'xref-find-apropos)
(global-set-key (kbd "A-/")		'dabbrev-completion)

(global-unset-key (kbd "C-s"))
(global-unset-key (kbd "C-r"))
(global-unset-key (kbd "C-M-s"))
(global-unset-key (kbd "C-M-r"))

;(global-set-key (kbd "C-s") 'isearch-forward-regexp)
;(global-set-key (kbd "C-r") 'isearch-backward-regexp)
;(global-set-key (kbd "C-M-s") 'isearch-forward)
;(global-set-key (kbd "C-M-r") 'isearch-backward)

(global-set-key (kbd "C-s") 'isearch-forward-regexp)
(global-set-key (kbd "C-r") 'isearch-backward-regexp)
(global-set-key (kbd "C-M-s") 'isearch-forward)
(global-set-key (kbd "C-M-r") 'isearch-backward)
